name: Verify

on:
  push:
    branches: [master]
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      warden: ${{ steps.filter.outputs.warden }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            warden:
              - 'warden/**'
              - '.github/workflows/**'

  verify-warden:
    needs: changes
    if: ${{ needs.changes.outputs.warden == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ShellCheck
        run: shellcheck warden/warden
